### ISSUE TITLE
date picker shows error erroneously

### ISSUE THREAD

**Issue by flynnplatt** [nasa/common-mapping-client#71]
When you use the inputs to change the date and hit `enter` the input underlines red, indicating an error even if the date change was successful

**Comment by AaronPlave** [comment]
Hmm, is this expected behavior?

![date_input_error](https://user-images.githubusercontent.com/4419607/41558458-c00ef124-72f5-11e8-8b1e-c9635b65bc58.gif)

**Comment by flynnplatt** [comment]
yeah, 2020 is outside the min/max date range
