### ISSUE TITLE
DedupePlugin has been removed from Webpack

### ISSUE THREAD

**Issue by flynnplatt** [nasa/common-mapping-client#8]
See migration notes: https://webpack.js.org/guides/migrating/#dedupeplugin-has-been-removed

Including the plugin spits warnings out in the build report but does not cause errors

**Comment by eaardal** [comment]
The link https://webpack.js.org/guides/migrating/#dedupeplugin-has-been-removed resolves to 404. Any alternative?

**Comment by skbolton** [comment]
@eaardal https://webpack.js.org/migrate/3/#dedupeplugin-has-been-removed
